package com.example.try_mvp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.try_mvp.db.User;
import com.example.try_mvp.db.Diary;

import com.example.try_mvp.db.UserDao;
import com.example.try_mvp.db.DiaryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig diaryDaoConfig;

    private final UserDao userDao;
    private final DiaryDao diaryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        diaryDao = new DiaryDao(diaryDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Diary.class, diaryDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        diaryDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

}
