package com.example.try_mvp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DIARY".
 */
@Entity
public class Diary {

    @Id(autoincrement = true)
    private Long id;
    private String title;
    private String discription;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Diary() {
    }

    public Diary(Long id) {
        this.id = id;
    }

    @Generated
    public Diary(Long id, String title, String discription) {
        this.id = id;
        this.title = title;
        this.discription = discription;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDiscription() {
        return discription;
    }

    public void setDiscription(String discription) {
        this.discription = discription;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
